// Wordlist for punct
// Automatically generated by `contrib`.
// Do not edit.
package wordlists

var Punct_list = []string{"!", "#", "$", "%", "&", "(", ")", "*", "+", ",", "-", ".", "/", ":", ";", "<", "=", ">", "?", "@", "[", "]", "^", "_", "{", "}"}
