// Wordlist for upper
// Automatically generated by `contrib`.
// Do not edit.
package wordlists

var Upper_list = []string{"A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"}
